const database = [
  {
    category: "musique",
    id: "mus1",
    src: "https://e.snmc.io/i/fullres/w/14935beeca74a336875924153dbaa2ab/8670627",
    artist: "Spock's Beard",
    release: "Feel Euphoria",
    subtitle: "The Spock's feeling young",
    content: `If you're comparing Spock's Beard to Genesis, then Feel Euphoria is to A Trick of the Tail as Snow is to The Lamb Lies Down On Broadway. In both cases, you have a situation where the charismatic frontman of the group has left after the band has just completed an ambitious double album, and the drummer (in this case Nick D'Virgilio) has stepped into the gap.
    Actually, in some ways Spock's Beard had it harder than Genesis. Sure, Peter Gabriel was important to Genesis - but he didn't exert such a heavy influence on the songwriting process as Neal Morse did in Spock's Beard before his departure. Genesis were fairly collaborative about how they did songwriting, whereas a large majority of Spock's Beard's material from The Light to Snow has Neal as the sole credited songwriter.
    This means that for Feel Euphoria Spock's Beard had not one challenge but two: not only did they have to bed in a new vocalist, but they also had to adapt to a new songwriting and recording process - without Neal's steady hand at the tiller, but also with the new creative opportunities which naturally arise in such a situation.
    The end result doesn't entirely sound like the earlier Beard, but it's not so far away either. The mixture of modern rock and classic prog influences is still there, but the proportions are subtly different, as are the selections of what exactly the band take from each of those worlds. Some of the more left-field influences - like musicals, gospel, and Latin music - that Neal would toss in from time to time are dialled back; other sounds which haven't been a major part of the Beard's fabric start to creep in. (There's an electronic edge to the opening sections of the starting track which feels particularly fresh to Spock's Beard.)
    Is it a masterwork on the level of, say, V? No. But under the circumstances, I don't think you could reasonably expect Spock's Beard to produce one - the odds were always in favour of this being a transitional album which was hampered by the adjustment they needed to make.
    At the same time, it's significantly better than I expected. I don't envy the Beard the position they were in, and I'm sure they must have had a long think about whether it would be better to take their time about putting out a followup in order to give themselves time to adjust to the shift in band chemistry and really work on honing some new material, or work quickly in order to maintain their momentum and send the message that they were here to stay. In the end, they had the confidence to take the latter approach, and Feel Euphoria is good enough that I think that gamble paid off.`,
    published: "Today",
  },

  {
    category: "jv",
    id: "jv1",
    src: "https://res.cloudinary.com/cook-becker/image/fetch/q_auto,f_auto,w_1920,e_sharpen/https://candb.com/site/candb/images/artwork/ico-cover-art-fumito-ueda-playstation.jpg",
    artist: "Team Ico",
    release: "Ico",
    subtitle: "The star(t) of a new era",
    content: `In an industry that has always run with the idea of "bigger, better, and faster", Ico was the milestone of the PS2-generation that implied the true future of video games lies in minimalism and player connectivity.
    You can almost feel the testosterone of a Gears fanboy spiking the Ico lovefest of recent years. The game, when played by the wrong person, can be outright offensive. "I've played Zelda, dammit! I know you can do more in a video game than this!" they might yell. The idea of Ico being a piece of art isn't reinforced by its overly sentimental fanbase, but by the way it feels completely alien to some players even though it remains grounded in gameplay not too distant from more popular titles.
    Ico's presence as minimal art can be narrowed down into a list: no HUD, IDM score, no real dialogue, etc. It's a matter of class. Team Ico who-- you guessed it! --developed Ico modeled the game entirely around what the core experience is and what would detract from it. The idea that your character cannot die in combat would break a The Legend of Zelda [ゼルダの伝説] game, but since Ico's main concern varies from those games it works as a strength. At Ico's core is the player's connection to Yorda, the girl you have at your side for the better part of the game, dragging her along every step of the way. While the audio and art direction are sublime, it is the core experience delivered through the platforming and puzzles that makes it a timeless adventure.
    Since the PlayStation-era, games have grown more and more obsessed with player connection through cinematic presentation. Instead of deep storytelling, Ico creates a tangible emotional connection in the player through subliminal elements. The way the controller vibrates when you grab hold of Yorda's hand, the loneliness of the game's world, and the haunting music all exhort an emotional reaction out of the player that most games would try to attempt forcefully via FMVs and lengthy cut-scenes. It's remarkable how well Ico works without these things, as only an hour into the game I would feel my heart rate escalate when I had to leave Yorda behind or when I had to make a jump I wasn't quite sure I could manage. I didn't know why I was at this castle, I didn't know who Yorda was, but I wanted to escape it with her by my side. Through crafting a believable world with elegant presentation, Ico turned the 8-bit joke of saving the princess into an actual concern.
    Between Metal Gear Solid 2: Sons of Liberty and Final Fantasy X [ファイナルファンタジーX], the PS2 era came into its own in 2001. Even with all Ico's heart and ambition, I can't say it's a superior game than those two. Yet, as a pure experience, Ico will forever be put in the hall of fame for the simplicity of its design (have I mention how the game is actually fun?) and its brilliant presentation. The "games as art" discussion has become null in recent years, between the chiptune scene and 8-bit decals in the walls of every nerd's home. Games have always been art. It wasn't until Ico that gamers got a real taste of games that stirred up emotion in the player through sheer interaction and existence in a different world.
    Ico's ending won't make you cry and the games making you feel lonely dates back to Metroid [メトロイド], but 2001 brought about the first game to fill gamers with an intangible connection to an unrealistic scenario. And, it was all done through the player convincing his or herself through a personal connection to the world, not in-game cinemas and plot devices.`,
    published: "Today"
  }
];

export default database;