import { format } from "date-fns";

const database = [
  {
    category: "mus",
    id: "mus1",
    src: "https://e.snmc.io/i/fullres/w/14935beeca74a336875924153dbaa2ab/8670627",
    artist: "Spock's Beard",
    release: "Feel Euphoria",
    subtitle: "The Spock's feeling young",
    content: `If you're comparing Spock's Beard to Genesis, then Feel Euphoria is to A Trick of the Tail as Snow is to The Lamb Lies Down On Broadway. In both cases, you have a situation where the charismatic frontman of the group has left after the band has just completed an ambitious double album, and the drummer (in this case Nick D'Virgilio) has stepped into the gap.
    Actually, in some ways Spock's Beard had it harder than Genesis. Sure, Peter Gabriel was important to Genesis - but he didn't exert such a heavy influence on the songwriting process as Neal Morse did in Spock's Beard before his departure. Genesis were fairly collaborative about how they did songwriting, whereas a large majority of Spock's Beard's material from The Light to Snow has Neal as the sole credited songwriter.
    This means that for Feel Euphoria Spock's Beard had not one challenge but two: not only did they have to bed in a new vocalist, but they also had to adapt to a new songwriting and recording process - without Neal's steady hand at the tiller, but also with the new creative opportunities which naturally arise in such a situation.
    The end result doesn't entirely sound like the earlier Beard, but it's not so far away either. The mixture of modern rock and classic prog influences is still there, but the proportions are subtly different, as are the selections of what exactly the band take from each of those worlds. Some of the more left-field influences - like musicals, gospel, and Latin music - that Neal would toss in from time to time are dialled back; other sounds which haven't been a major part of the Beard's fabric start to creep in. (There's an electronic edge to the opening sections of the starting track which feels particularly fresh to Spock's Beard.)
    Is it a masterwork on the level of, say, V? No. But under the circumstances, I don't think you could reasonably expect Spock's Beard to produce one - the odds were always in favour of this being a transitional album which was hampered by the adjustment they needed to make.
    At the same time, it's significantly better than I expected. I don't envy the Beard the position they were in, and I'm sure they must have had a long think about whether it would be better to take their time about putting out a followup in order to give themselves time to adjust to the shift in band chemistry and really work on honing some new material, or work quickly in order to maintain their momentum and send the message that they were here to stay. In the end, they had the confidence to take the latter approach, and Feel Euphoria is good enough that I think that gamble paid off.`,
    published: format(new Date(2023, 4, 3), 'yyyy/MM/dd'),
  },

  {
    category: "jv",
    id: "jv1",
    src: "https://res.cloudinary.com/cook-becker/image/fetch/q_auto,f_auto,w_1920,e_sharpen/https://candb.com/site/candb/images/artwork/ico-cover-art-fumito-ueda-playstation.jpg",
    artist: "Team Ico",
    release: "Ico",
    subtitle: "The star(t) of a new era",
    content: `In an industry that has always run with the idea of "bigger, better, and faster", Ico was the milestone of the PS2-generation that implied the true future of video games lies in minimalism and player connectivity.
    You can almost feel the testosterone of a Gears fanboy spiking the Ico lovefest of recent years. The game, when played by the wrong person, can be outright offensive. "I've played Zelda, dammit! I know you can do more in a video game than this!" they might yell. The idea of Ico being a piece of art isn't reinforced by its overly sentimental fanbase, but by the way it feels completely alien to some players even though it remains grounded in gameplay not too distant from more popular titles.
    Ico's presence as minimal art can be narrowed down into a list: no HUD, IDM score, no real dialogue, etc. It's a matter of class. Team Ico who-- you guessed it! --developed Ico modeled the game entirely around what the core experience is and what would detract from it. The idea that your character cannot die in combat would break a The Legend of Zelda [ゼルダの伝説] game, but since Ico's main concern varies from those games it works as a strength. At Ico's core is the player's connection to Yorda, the girl you have at your side for the better part of the game, dragging her along every step of the way. While the audio and art direction are sublime, it is the core experience delivered through the platforming and puzzles that makes it a timeless adventure.
    Since the PlayStation-era, games have grown more and more obsessed with player connection through cinematic presentation. Instead of deep storytelling, Ico creates a tangible emotional connection in the player through subliminal elements. The way the controller vibrates when you grab hold of Yorda's hand, the loneliness of the game's world, and the haunting music all exhort an emotional reaction out of the player that most games would try to attempt forcefully via FMVs and lengthy cut-scenes. It's remarkable how well Ico works without these things, as only an hour into the game I would feel my heart rate escalate when I had to leave Yorda behind or when I had to make a jump I wasn't quite sure I could manage. I didn't know why I was at this castle, I didn't know who Yorda was, but I wanted to escape it with her by my side. Through crafting a believable world with elegant presentation, Ico turned the 8-bit joke of saving the princess into an actual concern.
    Between Metal Gear Solid 2: Sons of Liberty and Final Fantasy X [ファイナルファンタジーX], the PS2 era came into its own in 2001. Even with all Ico's heart and ambition, I can't say it's a superior game than those two. Yet, as a pure experience, Ico will forever be put in the hall of fame for the simplicity of its design (have I mention how the game is actually fun?) and its brilliant presentation. The "games as art" discussion has become null in recent years, between the chiptune scene and 8-bit decals in the walls of every nerd's home. Games have always been art. It wasn't until Ico that gamers got a real taste of games that stirred up emotion in the player through sheer interaction and existence in a different world.
    Ico's ending won't make you cry and the games making you feel lonely dates back to Metroid [メトロイド], but 2001 brought about the first game to fill gamers with an intangible connection to an unrealistic scenario. And, it was all done through the player convincing his or herself through a personal connection to the world, not in-game cinemas and plot devices.`,
    published: format(new Date(2021, 4, 3), 'yyyy/MM/dd'),
  },

  {
    category: "lit",
    id: "lit1",
    src: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1621713120i/426504.jpg",
    artist: "Jorge Luis Borges",
    release: "Ficciones",
    subtitle: "A master class in magic realism",
    content: `The author is a master of mixing fantasy and philosophy. He has been credited as a pioneer in magical realism in Latin American literature. In this classic collection, most stories are almost as much essays as they are short stories.
    Recurring themes are non-existent and ancient books. Time. Geometry. Gnosticism. Mirrors. Encyclopedias. Chess. Labyrinths. Imaginary worlds. Memory and mnemonics. Infinity in books, libraries and labyrinths. All possible outcomes, like infinite universes in which every act and its result are mirrored by the opposite act and the opposite result. (Or maybe the opposite act and the same result. lol)
    Here are a few examples of the 17 stories:
    The Library of Babel, perhaps his best-known story combines almost all of the list in the previous paragraph. The library is God or the universe. Every book is mirrored by one with all the opposite conclusions.
    Tlon, Uqbar, Orbis Tertius is a story that gives us imaginary countries and worlds that get into encyclopedias and take on a life of their own. (Like imaginary islands) “One of the schools of Tlon has reached the point of denying time. It reasons that the present is undefined, that the future has no other reality than as present hope, that the past is no more than present memory.” (This story calls to mind the fake stories that keep resurfacing and periodically go viral on the internet. This week for example in Feb. 2019, fact checking sites are once again refuting claims that 98 million Americans got cancer from the polio vaccine.)
    In The Garden of Forking Paths, a Chinese spy for the Germans (against the British) can only pass on his secret information by killing someone. Meanwhile we hear speculation on the garden: is it a true labyrinth or a book about the labyrinth?
    In The Secret Miracle a man is condemned to the firing squad basically for being an erudite Jew. He tries to stop his execution by attempting to foresee all the details of the endless possibilities of the execution -- number of soldiers firing, how far away they stand, where it will take place, etc. -- knowing that it is impossible to imagine all these details correctly, so that if he imagines all possible scenarios, his execution can't happen. He prays for a year to finish the book he is working on. He is granted that wish to finish the book in his head in the suspension of time between bullets leaving the guns and their impact on his body.
    Three Versions of Judas is in effect a religious work arguing that Judas' betrayal of Christ was superfluous. His action wasn't needed to betray a master who daily preached in the synagogue and performed miracles before gatherings of thousands of people. But maybe the betrayal was necessary for God to prove his divinity.
    And we have humor:
    A hotel “…which most manifestly unites the hateful whiteness of a sanitorium, the numbered divisibility of a prison, and the general appearance of a bawdy house…”
    “This delay [in an execution] was due to a desire on the part of the authorities to act slowly and impersonally, in the manner of planets or vegetables.”
    “In life, he suffered from a sense of unreality, as do many Englishmen; dead, he is not even the ghostly creature he was then.”`,
    published: format(new Date(2023, 4, 4), 'yyyy/MM/dd'),
  },

  {
    category: "mus",
    id: "mus2",
    src: "https://e.snmc.io/i/fullres/w/a01831051de32d86f046dc99923b0275/10698076",
    artist: "Flying Lotus",
    release: "Cosmogramma",
    subtitle: "A timeless classic of loss, love, and spirituality expressed in the most boundary pushing fashion.",
    content: `Arriving at the turn of a decade, Flying Lotus' third full-length LP is molded by a unique era in his life. It comes two years after his Warp debut, Los Angeles, whose progressive percussion propelled Lotus as one of the most exciting producers of the time. But in the wake of the record's success laid tragedy. Lotus' aunt, the iconic Alice Coltrane, passed away shortly before the release of Los Angeles. A year and a half later, Lotus' mother would pass from diabetes complications. An artist always looking for new avenues, FlyLo used the tragedies as affirmation to go in a new direction as a producer.
    Cosmogramma reinvents many genres that inspire it, stepping away from what's found in its classic predecessors. It differs from the compilations of electronic classics like Aphex Twin's Selected Ambient Works and diverges from the beat-making library found in J Dilla's Donuts. The tracks bleed into each other and connect to create what FlyLo calls a “space opera”. While many genres come together to construct the theatrics, Cosmogramma's sound doesn't feel forced. Rather, the instruments, samples, and vocals feel like actors; necessary parts of the journey the listener is taken on. The track list itself ebbs into multiple phases, like acts of a play, conjoining different elements to create a bigger picture of cosmic self discovery.
    The initial phase encompasses the first three tracks on the album. The tracks are similar to what can be found on Los Angeles with their thumping rhythms and whizzing synths. However, they each carry an element that prepares the listener for the tracks to come. The opener Clock Catcher shakes your brain with an escalator of electronica. The buzzing intro dissolves as you experience a new for Flying Lotus, live instrumentation. As a listener, you now get a hint that this album is not like the last. A glittering harp soothes the track, almost preparing the mind for what's to come. This use of live instruments continues on Pickled! Thundercat delivers a meaty bass line as a train whistle spurs on top of it. It feels like riding a railway through a wormhole as the whistle becomes more and more distorted. The bassline acts as the bumpy tracks leading you to the world FlyLo creates. This track segways into the warping banger Nose Art. The synth leads whizz up and down like a seismograph giving the track an electric feel. Further back on the mix the song sounds like it's enveloping over itself and warping as the higher frequencies reverberate in and out. The vocal sample bellowing “watch this” makes this track feel like a sort of flex. It's as if FlyLo is cracking his fingers before the true intro. Some of the more spacey aspects and instrumental elements on this first section of the album prove to be important as the listen continues.
    Intro // A Cosmic Drama is a track that often gets overlooked despite its intriguing arrangement. The song is everything you want from an intro. Its stirring strings and harp glide as glimpses of what's to come play out. Undertones of bass can be heard as if they're pillaring in the distance, while some beeping sounds chirp through like a flock of birds flying by. It feels like discovering an ancient city, like something's awaiting you. At the same time, the live strings on top of the synths make it sound like an interstellar orchestra tuning its instruments. Either way, you're left feeling like something incredible is to come. You don't have to wait long for that though.
    The next three tracks are some of the most maximal on the record. Here, FlyLo incorporates much of his more IDM-orientated production. There's a multitude of common objects and sounds sampled to create the complex and other worldly beats found here. It's as if he's connecting the Earth to the stars. To convey this, the aptly named Zodiac Shit kicks off this three-track run. The first half of the song is a classic IDM beat. Breathing sounds bounce off the drums while other samples join in. The sounds of a room build up the track; door squeaking, the wobble of a stack of papers, or a plastic ruler, and a steady clicking similar to that of a keyboard. It all comes together to make an experience, like sitting at a desk job and watching your surroundings bend into the 4th dimension. This section of the track finishes symphonically as fluttering strings dance like seahorses over the beat. For the second half, FlyLo shows his versatility as a more hip-hop-inspired drum pattern takes over. Thundercat's bass line and Miguel Atwood-Ferguson's strings combine and create a galactic sound. The spaceship sounds and synths found here sound like FlyLo had a close encounter and remixed the whole thing. This combination of drums, synths, bass, and strings establishes what the album's sound will be. In representing what Cosmogramma achieves sonically, Zodiac Shit is an essential track.
    Computer Face // Pure Being is another iconic track from this project. This track functions as a tribute to FlyLo's innocent love for electronics, as well as his journey to becoming a great producer. The beat is built on this crooked whirring sound, it's like a toy robot starting up, malfunctioning, and promptly shutting down. It has no business being the backbone of a song, but FlyLo's genius makes it work. The synth leads give this song its humongous energy. Laser beams straight out of a video game shoot across the track, giving it an almost boyish feeling. As the track zooms through you can practically see a young Flying Lotus being sucked into the world of technology. The song cuts back for a second, before a yelp, like potential being realized, masterfully slams it all together. Without using any words, FlyLo takes the listener on his journey of discovering computers and becoming a master of them. The makeup of this track once again takes earthly things, arcade sounds and machinery, and launches them to the heavens.
    FlyLo continues to paint personal experiences through his soundscapes on the song …And The World Laughs With You. This song features vocals from Radiohead frontman Thom Yorke. All the vocal contributions on Cosmogramma bleed onto the production, but Yorke's is by far the most embedded. FlyLo has described the song's title as a reference to those around you leaving when times get tough. To achieve this, the song warps to convey a multitude of emotions. Yorke's relatively simple three line contribution is transformed as FlyLo streams his thoughts through it. Yorke croons, “I need to know you're out there”, the feeling of abandonment weighing down on the listener. The pitch is continuously shifted, the higher vocals giving an innocent beg to the line, the lower pitch showing a depressive loneliness. FlyLo is confused on this track; why did the people who supported him leave him at his worst? “And the world laughs with you”, echoes as Yorke becomes the devil and angel on one's shoulders. The high pitched line delivers like someone clinging to a moment, everyone around laughing and enjoying the happy time. The lower pitch feels like it's questioning itself, does that moment even matter if they aren't there now? The pitch shifting creates a feeling of doubt, and coupled with the icier production, it feels like you're on the brink of insanity. The track ends with a spiraling, eclectic finish, like taking a blunt shot of laughing gas. Despite the high-profile feature, Yorke is just another actor in FlyLo's opera, a tool he uses to express his personal experience. This track closes what feels like an opening act, the first stage before diving deeper into the world of Cosmogramma.
    Arkestry is a track that feels almost transitionary, like scuttling through a cave before finding the light at the other end. As the name suggests, it's a jazz-driven song. Its dusty drums rattle in ambiance before a tenor sax appears. The sax line seems to guide you through the song's darker environment. All the while, synth sounds twinkle in and out, sounding like a hidden swarm of bats. The song is eerie and cold, perfect for bridging into the more hypnotic section of the album.
    If Arkestry leads you deeper into the chasms, MmmHmm is what's waiting for you. The track features heavy contributions from Thundercat; he's both singing the vocals and playing the bassline on the track. In his usual falsetto, Thundercat gleams out, “It's plain to see for you and me”. The line repeats as the bassline tickles the underbelly of the song. On the production end, FlyLo once again toys with the vocals he's given. The lead here almost builds up and around Thundercat's vocals. It pokes back after every line, sometimes matching the sung note, sometimes shooting out sporadically like a solar flare. The dynamic gives the song a unique progression, like watching dueling comets dance in the sky. The song ends with some scatting over stripped-back strings, an ominous tone that sounds like you're walking into a space cult meeting. Somehow, it's the perfect entrance for one of the most enchanting tracks on the album, Do The Astral Plane. This is another genre-fusing track that showcases FlyLo's creativity. The song is built off a thumping house beat, backed by Marvin Gaye vocal samples. What FlyLo adds to this should absolutely not work, but it somehow creates a masterpiece. A hand crank is added for percussion, giving an IDM edge to the song. Strings elevate the song further while a trumpet flares in the background. There's some elegance with these elements, but the track gets turned on its head when the bass tones arrive. The buzzing lead sounds like it's coming from a planet-sized speaker. Despite the futuristic sound beneath it, there's an undeniable grime brought by the bass. The whole song sounds like a space rave.
    These themes continue on the song Satelllliiiiiteee. This track is also grimy and street influenced. It feels grey with filtered vocals passing, making it sound like something off of Burial's Untrue. The production is open, it's like staring out of a ship's porthole. A sense of dreamy wonder backgrounded by the vessel's mechanical ambiance. It phases into a hypnotic bassline that finishes out the track. If the first section of Cosmogramma joins FlyLo's personal life to the stars, this section shows him trying to find its place in the universe. Spirituality is known to be a major influence on the album, and these tracks have a mystic quality. MmmHmm and it's starry production, Do The Astral Plane and it's otherworldly prowess, Satelllliiiiiteee and its dreamlike soundscape; it's easy to assume these tracks were made while searching for answers.
    Looking back on the track list, the album feels like it's living, one holistic piece. 12 years on from this album's release, there's still nothing that really sounds like it. It's off-kilter and detailed, there's some memorable moments of glitchy bliss, but there's also minute features on the lowkey tracks that show the immense dedication put into this album. Most importantly, Cosmogramma is experimental in an organic way. It justifies its avant-garde nature with the vivid environments constructed. There's life breathed into every song. It's a piece about Steve Ellison finding his life, his loved ones, and his persona, Flying Lotus, and how they fit into the universe. In its futuristic and distinctive sound, Cosmogramma remains an album as timeless as the stars.`,
    published: format(new Date(2022, 2, 7), 'yyyy/MM/dd'),
  },
];

export default database;