import { format } from "date-fns";

const database = [
  {
    category: "mus",
    id: "mus1",
    src: "https://e.snmc.io/i/fullres/w/14935beeca74a336875924153dbaa2ab/8670627",
    artist: "Spock's Beard",
    release: "Feel Euphoria",
    subtitle: "The Spock's feeling young",
    content: `If you're comparing Spock's Beard to Genesis, then Feel Euphoria is to A Trick of the Tail as Snow is to The Lamb Lies Down On Broadway. In both cases, you have a situation where the charismatic frontman of the group has left after the band has just completed an ambitious double album, and the drummer (in this case Nick D'Virgilio) has stepped into the gap.
    Actually, in some ways Spock's Beard had it harder than Genesis. Sure, Peter Gabriel was important to Genesis - but he didn't exert such a heavy influence on the songwriting process as Neal Morse did in Spock's Beard before his departure. Genesis were fairly collaborative about how they did songwriting, whereas a large majority of Spock's Beard's material from The Light to Snow has Neal as the sole credited songwriter.
    This means that for Feel Euphoria Spock's Beard had not one challenge but two: not only did they have to bed in a new vocalist, but they also had to adapt to a new songwriting and recording process - without Neal's steady hand at the tiller, but also with the new creative opportunities which naturally arise in such a situation.
    The end result doesn't entirely sound like the earlier Beard, but it's not so far away either. The mixture of modern rock and classic prog influences is still there, but the proportions are subtly different, as are the selections of what exactly the band take from each of those worlds. Some of the more left-field influences - like musicals, gospel, and Latin music - that Neal would toss in from time to time are dialled back; other sounds which haven't been a major part of the Beard's fabric start to creep in. (There's an electronic edge to the opening sections of the starting track which feels particularly fresh to Spock's Beard.)
    Is it a masterwork on the level of, say, V? No. But under the circumstances, I don't think you could reasonably expect Spock's Beard to produce one - the odds were always in favour of this being a transitional album which was hampered by the adjustment they needed to make.
    At the same time, it's significantly better than I expected. I don't envy the Beard the position they were in, and I'm sure they must have had a long think about whether it would be better to take their time about putting out a followup in order to give themselves time to adjust to the shift in band chemistry and really work on honing some new material, or work quickly in order to maintain their momentum and send the message that they were here to stay. In the end, they had the confidence to take the latter approach, and Feel Euphoria is good enough that I think that gamble paid off.`,
    published: format(new Date(2023, 4, 3), 'yyyy/MM/dd'),
  },

  {
    category: "jv",
    id: "jv1",
    src: "https://res.cloudinary.com/cook-becker/image/fetch/q_auto,f_auto,w_1920,e_sharpen/https://candb.com/site/candb/images/artwork/ico-cover-art-fumito-ueda-playstation.jpg",
    artist: "Team Ico",
    release: "Ico",
    subtitle: "The star(t) of a new era",
    content: `In an industry that has always run with the idea of "bigger, better, and faster", Ico was the milestone of the PS2-generation that implied the true future of video games lies in minimalism and player connectivity.
    You can almost feel the testosterone of a Gears fanboy spiking the Ico lovefest of recent years. The game, when played by the wrong person, can be outright offensive. "I've played Zelda, dammit! I know you can do more in a video game than this!" they might yell. The idea of Ico being a piece of art isn't reinforced by its overly sentimental fanbase, but by the way it feels completely alien to some players even though it remains grounded in gameplay not too distant from more popular titles.
    Ico's presence as minimal art can be narrowed down into a list: no HUD, IDM score, no real dialogue, etc. It's a matter of class. Team Ico who-- you guessed it! --developed Ico modeled the game entirely around what the core experience is and what would detract from it. The idea that your character cannot die in combat would break a The Legend of Zelda [ゼルダの伝説] game, but since Ico's main concern varies from those games it works as a strength. At Ico's core is the player's connection to Yorda, the girl you have at your side for the better part of the game, dragging her along every step of the way. While the audio and art direction are sublime, it is the core experience delivered through the platforming and puzzles that makes it a timeless adventure.
    Since the PlayStation-era, games have grown more and more obsessed with player connection through cinematic presentation. Instead of deep storytelling, Ico creates a tangible emotional connection in the player through subliminal elements. The way the controller vibrates when you grab hold of Yorda's hand, the loneliness of the game's world, and the haunting music all exhort an emotional reaction out of the player that most games would try to attempt forcefully via FMVs and lengthy cut-scenes. It's remarkable how well Ico works without these things, as only an hour into the game I would feel my heart rate escalate when I had to leave Yorda behind or when I had to make a jump I wasn't quite sure I could manage. I didn't know why I was at this castle, I didn't know who Yorda was, but I wanted to escape it with her by my side. Through crafting a believable world with elegant presentation, Ico turned the 8-bit joke of saving the princess into an actual concern.
    Between Metal Gear Solid 2: Sons of Liberty and Final Fantasy X [ファイナルファンタジーX], the PS2 era came into its own in 2001. Even with all Ico's heart and ambition, I can't say it's a superior game than those two. Yet, as a pure experience, Ico will forever be put in the hall of fame for the simplicity of its design (have I mention how the game is actually fun?) and its brilliant presentation. The "games as art" discussion has become null in recent years, between the chiptune scene and 8-bit decals in the walls of every nerd's home. Games have always been art. It wasn't until Ico that gamers got a real taste of games that stirred up emotion in the player through sheer interaction and existence in a different world.
    Ico's ending won't make you cry and the games making you feel lonely dates back to Metroid [メトロイド], but 2001 brought about the first game to fill gamers with an intangible connection to an unrealistic scenario. And, it was all done through the player convincing his or herself through a personal connection to the world, not in-game cinemas and plot devices.`,
    published: format(new Date(2021, 4, 3), 'yyyy/MM/dd'),
  },

  {
    category: "lit",
    id: "lit1",
    src: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1621713120i/426504.jpg",
    artist: "Jorge Luis Borges",
    release: "Ficciones",
    subtitle: "A master class in magic realism",
    content: `The author is a master of mixing fantasy and philosophy. He has been credited as a pioneer in magical realism in Latin American literature. In this classic collection, most stories are almost as much essays as they are short stories.
    Recurring themes are non-existent and ancient books. Time. Geometry. Gnosticism. Mirrors. Encyclopedias. Chess. Labyrinths. Imaginary worlds. Memory and mnemonics. Infinity in books, libraries and labyrinths. All possible outcomes, like infinite universes in which every act and its result are mirrored by the opposite act and the opposite result. (Or maybe the opposite act and the same result. lol)
    Here are a few examples of the 17 stories:
    The Library of Babel, perhaps his best-known story combines almost all of the list in the previous paragraph. The library is God or the universe. Every book is mirrored by one with all the opposite conclusions.
    Tlon, Uqbar, Orbis Tertius is a story that gives us imaginary countries and worlds that get into encyclopedias and take on a life of their own. (Like imaginary islands) “One of the schools of Tlon has reached the point of denying time. It reasons that the present is undefined, that the future has no other reality than as present hope, that the past is no more than present memory.” (This story calls to mind the fake stories that keep resurfacing and periodically go viral on the internet. This week for example in Feb. 2019, fact checking sites are once again refuting claims that 98 million Americans got cancer from the polio vaccine.)
    In The Garden of Forking Paths, a Chinese spy for the Germans (against the British) can only pass on his secret information by killing someone. Meanwhile we hear speculation on the garden: is it a true labyrinth or a book about the labyrinth?
    In The Secret Miracle a man is condemned to the firing squad basically for being an erudite Jew. He tries to stop his execution by attempting to foresee all the details of the endless possibilities of the execution -- number of soldiers firing, how far away they stand, where it will take place, etc. -- knowing that it is impossible to imagine all these details correctly, so that if he imagines all possible scenarios, his execution can't happen. He prays for a year to finish the book he is working on. He is granted that wish to finish the book in his head in the suspension of time between bullets leaving the guns and their impact on his body.
    Three Versions of Judas is in effect a religious work arguing that Judas' betrayal of Christ was superfluous. His action wasn't needed to betray a master who daily preached in the synagogue and performed miracles before gatherings of thousands of people. But maybe the betrayal was necessary for God to prove his divinity.
    And we have humor:
    A hotel “…which most manifestly unites the hateful whiteness of a sanitorium, the numbered divisibility of a prison, and the general appearance of a bawdy house…”
    “This delay [in an execution] was due to a desire on the part of the authorities to act slowly and impersonally, in the manner of planets or vegetables.”
    “In life, he suffered from a sense of unreality, as do many Englishmen; dead, he is not even the ghostly creature he was then.”`,
    published: format(new Date(2019, 4, 4), 'yyyy/MM/dd'),
  },

  {
    category: "mus",
    id: "mus2",
    src: "https://e.snmc.io/i/fullres/w/a01831051de32d86f046dc99923b0275/10698076",
    artist: "Flying Lotus",
    release: "Cosmogramma",
    subtitle: "A timeless classic of loss, love, and spirituality expressed in the most boundary pushing fashion.",
    content: `Arriving at the turn of a decade, Flying Lotus' third full-length LP is molded by a unique era in his life. It comes two years after his Warp debut, Los Angeles, whose progressive percussion propelled Lotus as one of the most exciting producers of the time. But in the wake of the record's success laid tragedy. Lotus' aunt, the iconic Alice Coltrane, passed away shortly before the release of Los Angeles. A year and a half later, Lotus' mother would pass from diabetes complications. An artist always looking for new avenues, FlyLo used the tragedies as affirmation to go in a new direction as a producer.
    Cosmogramma reinvents many genres that inspire it, stepping away from what's found in its classic predecessors. It differs from the compilations of electronic classics like Aphex Twin's Selected Ambient Works and diverges from the beat-making library found in J Dilla's Donuts. The tracks bleed into each other and connect to create what FlyLo calls a “space opera”. While many genres come together to construct the theatrics, Cosmogramma's sound doesn't feel forced. Rather, the instruments, samples, and vocals feel like actors; necessary parts of the journey the listener is taken on. The track list itself ebbs into multiple phases, like acts of a play, conjoining different elements to create a bigger picture of cosmic self discovery.
    The initial phase encompasses the first three tracks on the album. The tracks are similar to what can be found on Los Angeles with their thumping rhythms and whizzing synths. However, they each carry an element that prepares the listener for the tracks to come. The opener Clock Catcher shakes your brain with an escalator of electronica. The buzzing intro dissolves as you experience a new for Flying Lotus, live instrumentation. As a listener, you now get a hint that this album is not like the last. A glittering harp soothes the track, almost preparing the mind for what's to come. This use of live instruments continues on Pickled! Thundercat delivers a meaty bass line as a train whistle spurs on top of it. It feels like riding a railway through a wormhole as the whistle becomes more and more distorted. The bassline acts as the bumpy tracks leading you to the world FlyLo creates. This track segways into the warping banger Nose Art. The synth leads whizz up and down like a seismograph giving the track an electric feel. Further back on the mix the song sounds like it's enveloping over itself and warping as the higher frequencies reverberate in and out. The vocal sample bellowing “watch this” makes this track feel like a sort of flex. It's as if FlyLo is cracking his fingers before the true intro. Some of the more spacey aspects and instrumental elements on this first section of the album prove to be important as the listen continues.
    Intro // A Cosmic Drama is a track that often gets overlooked despite its intriguing arrangement. The song is everything you want from an intro. Its stirring strings and harp glide as glimpses of what's to come play out. Undertones of bass can be heard as if they're pillaring in the distance, while some beeping sounds chirp through like a flock of birds flying by. It feels like discovering an ancient city, like something's awaiting you. At the same time, the live strings on top of the synths make it sound like an interstellar orchestra tuning its instruments. Either way, you're left feeling like something incredible is to come. You don't have to wait long for that though.`,
    published: format(new Date(2015, 2, 7), 'yyyy/MM/dd'),
  },
];

export default database;